site_name: Kelowna Islamic Center
site_url: https://mydomain.org/docs

docs_dir: content
site_dir: docs

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/index.md
      - Application Architecture: architecture/application-architecture.md
      - Internationalization: architecture/internationalization.md
      - Accessibility: architecture/accessibility.md
      - Design Language: architecture/design-language.md

  - Server Side:
      - Overview: server-side/index.md
      - Cloud Functions: server-side/cloud-functions.md
      - Prayer Times API: server-side/prayer-times-api.md
      - Announcements: server-side/announcements.md
      - Prayer Reminders: server-side/prayer-reminders.md
      - Development:
          - Installation: server-side/development/installation.md
          - Deployment: server-side/development/deployment.md
      - Cloud Functions Reference:
        - PrayerTimesFetch: server-side/cloud-functions/prayer-times-fetch.md
        - AnnouncementAlert: server-side/cloud-functions/announcement-alert.md
        - PrayerTimesAlertScheduler: server-side/cloud-functions/prayer-times-alert-scheduler.md
        - SendPrayerAlert: server-side/cloud-functions/send-prayer-alert.md

  - Mobile App:
      - Overview: mobile-app/index.md
      - Architecture:
        - Application Architecture: mobile-app/architecture/application-architecture.md
        - Background Services: mobile-app/architecture/background-services.md
        - Admin Tools: mobile-app/architecture/admin-tools.md
        - Notifications: mobile-app/architecture/notifications.md
      - Development:
        - Installation: mobile-app/development/installation.md
        - Android Setup: mobile-app/development/android-setup.md
        - iOS Setup: mobile-app/development/ios-setup.md
        - Building: mobile-app/development/building.md
        - Distribution: mobile-app/development/distribution.md

  - Kiosk App:
      - Overview: kiosk-app/index.md
      - Installation: kiosk-app/installation.md
      - Deployment: kiosk-app/deployment.md
      - Display Guide: kiosk-app/display-guide.md

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: light green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# 🔹 Repo link in top bar
repo_url: https://github.com/Kelowna-Islamic-Center
repo_name: View Repos on Github
repo_icon: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg